# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: double-quote-string-fixer
          - id: end-of-file-fixer
          - id: file-contents-sorter
    - repo: https://github.com/hhatto/autopep8
      rev: v2.0.4
      hooks:
          - id: autopep8
            args: [--global-config=pyproject.toml, --in-place]
            verbose: true
    - repo: https://github.com/pycqa/isort
      rev: 5.13.0
      hooks:
          - id: isort
            name: isort (python)
